### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by evliu** [fxxing/anki-json-importer#1]
``` ruby
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/webview.pyc", line 21, in link
  File "aqt/deckbrowser.pyc", line 47, in _linkHandler
  File "aqt/main.pyc", line 764, in onImport
  File "aqt/importing.pyc", line 272, in onImport
  File "aqt/importing.pyc", line 288, in importFile
  File "/Users/ev/Documents/Anki/addons/Json_Importer.py", line 22, in __init__
    self.mappingFields = [f['name'] for f in self.model['flds']]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Hi, I'm trying to just import the sample `[{"field1":"value1","field2":"value2"}]` and get the error above. Am I doing something wrong? Thx!

**Comment by fxxing** [comment]
Please check:
1. Must has a node type named "JsonImporter"
2. All the fields in json file must have corresponding field in "JsonImporter" node.

**Comment by evliu** [comment]
thx for the quick reply. I'm new to using Anki, but I realized CSV import is pretty easy so I just used an online json -> csv converter and imported that with no issues at all. Thx again!
